import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { EvidenceViewer } from "../views/EvidenceViewer";

const BUNDLE = {
  id: "b1", domain_id: 1, campaign_id: null, bundle_root: "c8e1a4f0" + "0".repeat(56), signature: "sig",
  collector_pk: "ed25519:pk", partial: false, created_at: "2026-10-06T00:00:00Z", anchored_tx: null, anchored_at: null,
  artifacts: [
    { name: "dom.html", sha256: "a4f2c9" + "0".repeat(58), size_bytes: 31204, url: "/evidence/b1/artifacts/dom.html" },
    { name: "screenshot.png", sha256: "3f2a91" + "0".repeat(58), size_bytes: 867234, url: "/x" },
  ],
};
const TAMPERED = {
  valid: false, root_matches: false, signature_valid: true, expected_root: BUNDLE.bundle_root, computed_root: "5e88b1" + "0".repeat(58),
  failures: [{ artifact: "dom.html", expected: "a4f2c9" + "0".repeat(58), found: "5e88b1" + "0".repeat(58), reason: "hash_mismatch" }],
};

function mount(verify: unknown) {
  global.fetch = vi.fn((url: string) => {
    const body = url.endsWith("/verify") ? verify : url.endsWith("/report")
      ? { bundle_id: "b1", recipient: null, format: "markdown", body: "## Phishing report\n…\nGenerated by QCertChain — not sent.", sent: false, generated_at: "x" }
      : BUNDLE;
    return Promise.resolve(new Response(JSON.stringify(body), { status: 200 }));
  }) as never;
  const qc = new QueryClient();
  return render(<QueryClientProvider client={qc}><EvidenceViewer bundleId="b1" /></QueryClientProvider>);
}

it("tamper: the failing artifact row turns red and shows both hashes", async () => {
  mount(TAMPERED);
  await screen.findByText("dom.html");
  fireEvent.click(screen.getByRole("button", { name: /verify/i }));
  const row = await screen.findByTestId("artifact-dom.html");
  await waitFor(() => expect(row.getAttribute("style")).toContain("var(--v-confirmed)"));
  expect(row.textContent).toContain("a4f2c9");
  expect(row.textContent).toContain("5e88b1");
  expect(row.textContent).toMatch(/TAMPERED/);
  expect(screen.getByTestId("artifact-screenshot.png").getAttribute("style") ?? "").not.toContain("--v-confirmed");
  expect(screen.getByText(/root mismatch/i)).toBeInTheDocument();
});

it("untouched bundle verifies", async () => {
  mount({ valid: true, root_matches: true, signature_valid: true, failures: [] });
  await screen.findByText("dom.html");
  fireEvent.click(screen.getByRole("button", { name: /verify/i }));
  await screen.findByText(/signature valid/i);
});

it("the report is labelled as never sent", async () => {
  mount(TAMPERED);
  await screen.findByText("dom.html");
  fireEvent.click(screen.getByRole("button", { name: /report/i }));
  await screen.findByText(/Report generated — not sent/);
});
