/** Every term a viewer meets on the console, defined once. The tour cards and the ? panels both list the terms of
 *  their page from here (owner request 2026-10-09: "explain what IOC, corroborate... are in each step"). */
export interface Term { term: string; meaning: string }

export const GLOSSARY = {
  ct: { term: "Certificate Transparency", meaning: "Public, append-only logs where every HTTPS certificate is published. Browsers reject a certificate that is not logged, so an attacker who wants a padlock must announce the domain there first." },
  statusSquare: { term: "Status square", meaning: "Each stage reports in every few seconds. Filled is ok, half-filled degraded, crossed and grey failed, hollow no report yet." },
  triage: { term: "Triage", meaning: "The fast first filter. It scores every new name against the brands it protects and nominates the suspicious ones; it never decides." },
  candidate: { term: "Candidate", meaning: "A domain triage nominated. Suspicious, not verified, and never shown in red." },
  source: { term: "Source", meaning: "Where the name came from: the live certificate stream, a recorded replay, a link in an analysed email, or the seeded demo campaigns." },
  score: { term: "Triage score", meaning: "From zero to one. Above the threshold a name becomes a candidate; a lower threshold costs page fetches, not accusations." },
  brandToken: { term: "Brand token", meaning: "A word that identifies a protected brand, such as its name, found inside the domain." },
  homograph: { term: "Homograph", meaning: "A name that looks like the brand's but uses look-alike characters, for example a Cyrillic letter in place of a Latin one." },
  tld: { term: "Top-level domain", meaning: "The last part of the name, such as .com or .top. Some are cheap and favoured for phishing, which raises the score." },
  confirmed: { term: "Confirmed", meaning: "The page was fetched and two independent strong signals were found. The database rejects a confirmation with fewer." },
  strongSignal: { term: "Strong signal", meaning: "Evidence that on its own points to phishing, such as a cloned login form or passwords sent to a foreign site." },
  independent: { term: "Independent", meaning: "From different detectors and sharing no artifact, so one finding can never count twice." },
  campaign: { term: "Campaign", meaning: "Domains run by one operator, found by the infrastructure they share." },
  infraNode: { term: "Infrastructure node", meaning: "Something domains share: a hosting address, the network that owns it, a nameserver, a registrar, a certificate issuer, or a phishing-kit fingerprint." },
  kitHash: { term: "Kit hash", meaning: "A fingerprint of the phishing page's structure. Domains built from the same phishing kit share it, which is how one operator's work is recognised across organisations." },
  takedown: { term: "Takedown", meaning: "A request to a hosting provider, DNS provider or registrar to stop serving everything on one target, which takes its domains offline." },
  budget: { term: "Takedown budget", meaning: "How many takedown requests you can make. The planner picks which ones." },
  coverage: { term: "Coverage", meaning: "How many of the campaign's domains the chosen takedowns would take offline." },
  reachable: { term: "Reachable", meaning: "Domains some takedown can hit. Domains that sit only on shared infrastructure, such as a large DNS provider nobody would ask to act, cannot be reached at any budget." },
  npHard: { term: "NP-hard", meaning: "No known method finds the best plan quickly for every campaign: the number of possible plans grows explosively with the targets. That is why the solver matters." },
  cpsat: { term: "CP-SAT", meaning: "The constraint solver from Google OR-Tools. It finds the best plan and is what production uses." },
  greedy: { term: "Greedy", meaning: "Takes the target that covers the most remaining domains, one at a time. Fast, but not always the best plan." },
  annealing: { term: "Simulated annealing", meaning: "A randomised search that sometimes accepts a worse plan to escape a dead end." },
  qubo: { term: "QUBO", meaning: "The problem written as yes-or-no choices with pairwise costs. The same formulation runs on QAOA as a benchmark." },
  gap: { term: "Gap to CP-SAT", meaning: "How many fewer domains a solver's plan covers than the best plan." },
  abuseReport: { term: "Abuse report", meaning: "A request asking a provider to act, with the evidence attached. Generated for review, never sent." },
  route: { term: "Route", meaning: "Whom to ask: hosting abuse for an address, DNS abuse for a nameserver, registrar suspension for a registrar." },
  artifact: { term: "Artifact", meaning: "One piece of evidence: the screenshot, the page, the certificate, the DNS records or the WHOIS record." },
  fileHash: { term: "SHA-256 hash", meaning: "A fingerprint of a file. Change one byte and the fingerprint changes completely." },
  merkleRoot: { term: "Merkle root", meaning: "One hash that summarises all the artifact hashes, built by hashing them in pairs up to a single value." },
  signature: { term: "Ed25519 signature", meaning: "Proof that the collector produced this root and that nothing changed since." },
  anchored: { term: "Anchored", meaning: "The root was written to the chain with a timestamp nobody can change later." },
  iocRoot: { term: "IOC root", meaning: "A single hash over the campaign's indicators of compromise: its domains and the infrastructure they share. It commits to the exact list without revealing any of it." },
  corroborate: { term: "Corroborate", meaning: "Your organisation confirms it sees the same campaign. The answer is signed with your organisation's own chain key, so nobody can give it in your name. You cannot corroborate your own report." },
  dispute: { term: "Dispute", meaning: "Your organisation says the report looks wrong, signed the same way." },
  transaction: { term: "Transaction", meaning: "The chain's record of the publication. Its hash identifies it on the chain." },
  confidence: { term: "Confidence", meaning: "How sure the reporting organisation's clustering was that these domains belong to one campaign." },
  precision: { term: "Precision", meaning: "Of the domains flagged, the share that really are phishing." },
  recall: { term: "Recall", meaning: "Of the real phishing domains, the share that were flagged." },
  baseRate: { term: "Base rate", meaning: "How rare phishing is among all new certificates. At a realistic base rate precision is far lower than on a balanced test set, which is why triage only nominates." },
  leadTime: { term: "Lead time", meaning: "How much earlier a domain was seen in Certificate Transparency than in a public phishing feed." },
} satisfies Record<string, Term>;

export type TermId = keyof typeof GLOSSARY;
