// GENERATED by scripts/build_measured.py from reports/metrics.json and reports/api_latency.json: never edit by
// hand. Regenerate with `python -m scripts.build_measured` (npm run finalize does it too).

export type MeasuredId = "relay" | "triage" | "candidate" | "verdict" | "plan" | "verify";
export interface MeasuredStep {
  id: MeasuredId; stat: "median" | "p95"; value: string; p95: string | null; n: string | null; unit: string;
  at: string | null; unreachable: string | null; slowest: string | null;
}

/** The pipeline's measured steps, in pipeline order. A step that was not measured is absent. */
export const MEASURED: MeasuredStep[] = [
  {
    "id": "relay",
    "stat": "median",
    "value": "21 s",
    "p95": "30 s",
    "n": "114",
    "unit": "domains",
    "at": "6 October 2026",
    "unreachable": null,
    "slowest": null
  },
  {
    "id": "triage",
    "stat": "median",
    "value": "0.29 ms",
    "p95": "1.5 ms",
    "n": "200,000",
    "unit": "names",
    "at": "6 October 2026",
    "unreachable": null,
    "slowest": null
  },
  {
    "id": "candidate",
    "stat": "median",
    "value": "2.1 s",
    "p95": "5.4 s",
    "n": "114",
    "unit": "domains",
    "at": "6 October 2026",
    "unreachable": null,
    "slowest": null
  },
  {
    "id": "verdict",
    "stat": "median",
    "value": "1.6 s",
    "p95": "23 s",
    "n": "106",
    "unit": "domains",
    "at": "6 October 2026",
    "unreachable": "102 of 114",
    "slowest": null
  },
  {
    "id": "plan",
    "stat": "median",
    "value": "131 ms",
    "p95": null,
    "n": "5",
    "unit": "runs",
    "at": "6 October 2026",
    "unreachable": null,
    "slowest": "4.5 s"
  },
  {
    "id": "verify",
    "stat": "p95",
    "value": "139 ms",
    "p95": null,
    "n": null,
    "unit": "requests",
    "at": null,
    "unreachable": null,
    "slowest": null
  }
];

/** Certificate logged to candidate stored, end to end (median), and the part spent in the public relay. */
export const CT_TO_CANDIDATE: { value: string; relay: string; n: string } | null = {
  "value": "24 s",
  "relay": "21 s",
  "n": "114"
};
