"""Render the home page's step times (apps/console/src/explain/measured.ts) from reports/metrics.json and
reports/api_latency.json. Owner rule: no number is ever typed into what we publish; owner decision 2026-10-10: the
home page shows how long each step takes, from our own runs, and makes no speed claim against blocklists.

    PYTHONPATH=. python -m scripts.build_measured

A step that was not measured is left out, never estimated. Anchoring time is not shown: its measurement includes time
queued while the anchor worker was not running. `npm run finalize` and `scripts.build_report` run this too.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "apps/console/src/explain/measured.ts"
VERIFY_ROUTE = "org1 GET evidence/verify"


def secs(x: float) -> str:
    """A duration in seconds, as people read it: 0.29 ms, 131 ms, 2.1 s, 21 s."""
    x = float(x)
    if x < 1:
        ms = x * 1000
        return f"{ms:.2f} ms" if ms < 1 else f"{ms:.1f} ms" if ms < 10 else f"{round(ms)} ms"
    return f"{x:.1f} s" if x < 10 else f"{round(x)} s"


def count(n) -> str:
    return f"{int(n):,}"


def day(iso: str | None) -> str | None:
    if not iso:
        return None
    d = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
    return f"{d.day} {d:%B %Y}"


def _measured(d) -> bool:
    return isinstance(d, dict) and isinstance(d.get("p50"), (int, float))


def _step(id_: str, *, value: str, unit: str, stat: str = "median", p95: str | None = None, n: str | None = None,
          at: str | None = None, unreachable: str | None = None, slowest: str | None = None) -> dict:
    return {"id": id_, "stat": stat, "value": value, "p95": p95, "n": n, "unit": unit, "at": at,
            "unreachable": unreachable, "slowest": slowest}


def steps(metrics: dict, latency: dict) -> list[dict]:
    """The pipeline's measured steps, in pipeline order."""
    rt = metrics.get("response_time") or {}
    at = day(rt.get("measured_at"))
    out = []
    if _measured(r := rt.get("upstream_aggregator_delay_s")):
        out.append(_step("relay", value=secs(r["p50"]), p95=secs(r["p95"]), n=count(r["n"]), unit="domains", at=at))
    if _measured(t := (metrics.get("triage_rules") or {}).get("latency_us_per_name")):
        out.append(_step("triage", value=secs(t["p50"] / 1e6), p95=secs(t["p95"] / 1e6), n=count(t["n"]),
                         unit="names", at=day(t.get("measured_at"))))
    if _measured(c := rt.get("our_receipt_to_candidate_s")):
        out.append(_step("candidate", value=secs(c["p50"]), p95=secs(c["p95"]), n=count(c["n"]), unit="domains",
                         at=at))
    if _measured(v := rt.get("candidate_to_verdict_s")):
        by = rt.get("verdicts_from_live_candidates") or {}
        unreachable = f"{by['unreachable']} of {sum(by.values())}" if by.get("unreachable") else None
        out.append(_step("verdict", value=secs(v["p50"]), p95=secs(v["p95"]), n=count(v["n"]), unit="domains",
                         at=at, unreachable=unreachable))
    if _measured(p := rt.get("interdiction_cpsat_solve_ms_api")):
        out.append(_step("plan", value=secs(p["p50"] / 1000), n=count(p["n"]), unit="runs", at=at,
                         slowest=secs(p["max"] / 1000) if p.get("max") else None))
    if isinstance(ms := (latency.get(VERIFY_ROUTE) or {}).get("p95_ms"), (int, float)):
        out.append(_step("verify", stat="p95", value=secs(ms / 1000), unit="requests"))
    return out


def ct_to_candidate(metrics: dict) -> dict | None:
    rt = metrics.get("response_time") or {}
    total, relay = rt.get("ct_seen_to_candidate_s"), rt.get("upstream_aggregator_delay_s")
    if not (_measured(total) and _measured(relay)):
        return None
    return {"value": secs(total["p50"]), "relay": secs(relay["p50"]), "n": count(total["n"])}


def render(metrics: dict, latency: dict) -> str:
    j = lambda x: json.dumps(x, indent=2, ensure_ascii=False)  # noqa: E731
    return f"""// GENERATED by scripts/build_measured.py from reports/metrics.json and reports/api_latency.json: never edit by
// hand. Regenerate with `python -m scripts.build_measured` (npm run finalize does it too).

export type MeasuredId = "relay" | "triage" | "candidate" | "verdict" | "plan" | "verify";
export interface MeasuredStep {{
  id: MeasuredId; stat: "median" | "p95"; value: string; p95: string | null; n: string | null; unit: string;
  at: string | null; unreachable: string | null; slowest: string | null;
}}

/** The pipeline's measured steps, in pipeline order. A step that was not measured is absent. */
export const MEASURED: MeasuredStep[] = {j(steps(metrics, latency))};

/** Certificate logged to candidate stored, end to end (median), and the part spent in the public relay. */
export const CT_TO_CANDIDATE: {{ value: string; relay: string; n: string }} | null = {j(ct_to_candidate(metrics))};
"""


def write(metrics: dict, latency: dict, out: Path = OUT) -> Path:
    out.write_text(render(metrics, latency), encoding="utf-8", newline="\n")
    return out


def main() -> int:
    metrics = json.loads((ROOT / "reports/metrics.json").read_text(encoding="utf-8"))
    lat = ROOT / "reports/api_latency.json"
    latency = json.loads(lat.read_text(encoding="utf-8")) if lat.exists() else {}
    print(f"wrote {write(metrics, latency).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
