"""EXPLAIN (ANALYZE, BUFFERS) of the hottest API queries on the seeded datasets of both orgs -> docs/QUERY_PLANS.md.

Each statement is captured from a real request (so it is exactly what the API runs) and explained under the same
org binding the request used (role qcc_app + app.org_id), so row-level security is in the plan.
Usage: python -m scripts.explain_hot
"""
from __future__ import annotations

import tempfile
import time
from pathlib import Path

import sqlalchemy as sa

from scripts.bench_api import seeded_client
from services.config import ROOT, SETTINGS

SCOPE = ("select set_config(", "reset role")
HOT = [("Candidate list (live queue)", "GET", "/candidates?limit=50"),
       ("Campaign list", "GET", "/campaigns"),
       ("Campaign graph (snapshot read)", "GET", "/campaigns/{c}/graph"),
       ("Budget sweep (slider)", "GET", "/campaigns/{c}/sweep"),
       ("Domain detail", "GET", "/domains/{d}")]


def main() -> None:
    out = ["# Query plans: the five hottest API queries", "",
           "Generated by `python -m scripts.explain_hot` against the seeded datasets (org 1: 400 domains, org 2: 50).",
           "Each statement is the one the API actually ran for the request, explained under the same org binding",
           "(role `qcc_app`, `app.org_id` set), so row-level security is part of every plan.", ""]
    with tempfile.TemporaryDirectory() as tmp, seeded_client(SETTINGS.test_database_url, Path(tmp)) as (cl, keys, camps, conn):
        time.sleep(5)
        conn.exec_driver_sql("analyze")  # fresh statistics, as autovacuum would have in production
        h = {"X-API-Key": keys["org1"]}
        g = cl.get(f"/campaigns/{camps['org1']}/graph", headers=h).json()
        cl.get(f"/campaigns/{camps['org1']}/sweep", headers=h)
        stmts: list = []

        def on(c, cur, statement, params, ctx, many):
            stmts.append((statement, params))
        for title, method, path in HOT:
            path = path.format(c=camps["org1"], d=g["domains"][0][0])
            stmts.clear()
            sa.event.listen(conn, "before_cursor_execute", on)
            try:
                assert cl.request(method, path, headers=h).status_code == 200
            finally:
                sa.event.remove(conn, "before_cursor_execute", on)
            data = [(s, p) for s, p in stmts if not s.lstrip().lower().startswith(SCOPE)]
            assert len(data) == 1, (title, len(data))
            stmt, params = data[0]
            sp = conn.begin_nested()
            try:
                conn.exec_driver_sql("select set_config('app.org_id', '1', true), set_config('role', 'qcc_app', true)")
                plan = conn.exec_driver_sql("explain (analyze, buffers) " + stmt, params).scalars().all()
            finally:
                sp.rollback()
            out += [f"## {title}", "", f"`{method} {path.split('?')[0]}`", "", "```sql", stmt.strip(), "```", "",
                    "```", *plan, "```", ""]
    (ROOT / "docs/QUERY_PLANS.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote docs/QUERY_PLANS.md")


if __name__ == "__main__":
    main()
