"""Registrar-ready abuse report, rendered as Markdown. WRITTEN TO DISK, NEVER SENT (CLAUDE.md §2.1).

Nothing in this package sends email, posts forms or calls registrar APIs.
"""
from __future__ import annotations

from datetime import datetime

from evidence.bundle import Bundle


def render_abuse_report(*, domain: str, recipient: str | None, bundle: Bundle, signals: list[dict],
                        enrichment: dict, campaign_label: str | None, generated_at: datetime) -> str:
    lines = [
        "## Phishing report",
        "",
        f"**Domain:** `{domain}`",
        f"**Intended recipient (informational):** {recipient or 'unknown — no abuse contact in RDAP'}",
        f"**Campaign:** {campaign_label or 'not clustered'}",
        f"**Generated:** {generated_at.isoformat()}",
        "",
        "### Evidence (each signal is an observed fact)",
        "",
    ]
    for s in signals:
        lines.append(f"- **{s['strength']}** · {s['name']} — {s['detail']}")
    lines += ["", "### Infrastructure", ""]
    for k in ("ip_addresses", "asn", "asn_name", "nameservers", "registrar", "registered_at", "cert_issuer"):
        if enrichment.get(k):
            lines.append(f"- {k}: {enrichment[k]}")
    lines += ["", "### Evidence bundle", "",
              f"- Bundle id: `{bundle.bundle_id}`",
              f"- Merkle root (SHA-256, leaves sorted by name): `{bundle.root}`",
              f"- Ed25519 signature over the root: `{bundle.signature}`",
              f"- Collector public key: `{bundle.collector_pk}`",
              f"- Partial bundle: {'yes — some artifacts could not be collected' if bundle.partial else 'no'}",
              "", "| Artifact | SHA-256 | Bytes |", "|---|---|---:|"]
    for a in bundle.artifacts:
        lines.append(f"| {a.name} | `{a.sha256}` | {a.size_bytes} |")
    lines += ["", "---", "Generated by QCertChain — not sent."]
    return "\n".join(lines) + "\n"
