"""RELEASE GATE (CLAUDE.md §6): a tampered artifact invalidates the Merkle root; a wrong key fails the signature."""
from datetime import datetime, timezone
from pathlib import Path

import nacl.signing
import pytest

from evidence.bundle import build_bundle, verify_bundle
from evidence.merkle import leaf_hash, merkle_root
from evidence.report import render_abuse_report

KEY = nacl.signing.SigningKey.generate()
SK = KEY.encode().hex()
ARTS = {"dom.html": b"<html>kit</html>", "headers.json": b"{}", "screenshot.png": b"\x89PNG..."}


def mk(tmp_path):
    b = build_bundle(tmp_path, "b1", ARTS, SK)
    return b, {a.name: a.sha256 for a in b.artifacts}


def test_roundtrip_valid(tmp_path):
    b, exp = mk(tmp_path)
    r = verify_bundle(Path(b.dir), b.root, b.signature, b.collector_pk, exp)
    assert r.valid and r.root_matches and r.signature_valid and r.failures == []
    assert b.collector_pk == "ed25519:" + KEY.verify_key.encode().hex()


def test_one_byte_tamper_names_the_artifact(tmp_path):
    b, exp = mk(tmp_path)
    p = Path(b.dir) / "dom.html"
    data = bytearray(p.read_bytes())
    data[3] ^= 1
    p.write_bytes(bytes(data))
    r = verify_bundle(Path(b.dir), b.root, b.signature, b.collector_pk, exp)
    assert not r.valid and not r.root_matches and r.signature_valid
    assert [(f.artifact, f.reason) for f in r.failures] == [("dom.html", "hash_mismatch")]
    assert r.failures[0].expected == exp["dom.html"] != r.failures[0].found
    assert r.computed_root != r.expected_root == b.root


def test_wrong_key_fails_signature(tmp_path):
    b, exp = mk(tmp_path)
    other = "ed25519:" + nacl.signing.SigningKey.generate().verify_key.encode().hex()
    r = verify_bundle(Path(b.dir), b.root, b.signature, other, exp)
    assert not r.signature_valid and not r.valid and r.root_matches


def test_forged_root_with_valid_artifacts_fails_signature(tmp_path):
    b, exp = mk(tmp_path)
    r = verify_bundle(Path(b.dir), "00" * 32, b.signature, b.collector_pk, exp)
    assert not r.valid and not r.signature_valid and not r.root_matches


def test_deleted_artifact_reported_missing(tmp_path):
    b, exp = mk(tmp_path)
    (Path(b.dir) / "headers.json").unlink()
    r = verify_bundle(Path(b.dir), b.root, b.signature, b.collector_pk, exp)
    assert ("headers.json", "missing") in [(f.artifact, f.reason) for f in r.failures] and not r.valid


def test_extra_file_reported_unexpected(tmp_path):
    b, exp = mk(tmp_path)
    (Path(b.dir) / "injected.js").write_bytes(b"alert(1)")
    r = verify_bundle(Path(b.dir), b.root, b.signature, b.collector_pk, exp)
    assert ("injected.js", "unexpected") in [(f.artifact, f.reason) for f in r.failures] and not r.valid


def test_root_independent_of_insertion_order(tmp_path):
    a = build_bundle(tmp_path / "a", "x", ARTS, SK)
    b = build_bundle(tmp_path / "b", "x", dict(reversed(list(ARTS.items()))), SK)
    assert a.root == b.root


def test_renaming_an_artifact_changes_the_root():
    import hashlib
    h = hashlib.sha256(b"same").digest()
    assert merkle_root([leaf_hash("a.html", h)]) != merkle_root([leaf_hash("b.html", h)])


def test_merkle_odd_and_empty():
    import hashlib
    leaves = [hashlib.sha256(bytes([i])).digest() for i in range(3)]
    assert len(merkle_root(leaves)) == 32 and merkle_root([]) == hashlib.sha256(b"").digest()


def test_artifact_names_cannot_escape_bundle_dir(tmp_path):
    with pytest.raises(ValueError):
        build_bundle(tmp_path, "b2", {"../escape.txt": b"x"}, SK)


def test_report_never_says_sent(tmp_path):
    b, _ = mk(tmp_path)
    md = render_abuse_report(domain="icici-verify-kyc.top", recipient="abuse@registrar.example", bundle=b,
                             signals=[{"name": "credential_post_foreign_origin", "strength": "strong",
                                       "detail": "form POST -> 203.0.113.9"}],
                             enrichment={"registrar": "Registrar A (seed)"}, campaign_label="CAMP-0001",
                             generated_at=datetime(2026, 10, 6, tzinfo=timezone.utc))
    assert "icici-verify-kyc.top" in md and b.root in md
    assert all(a.sha256 in md for a in b.artifacts)
    assert "Generated by QCertChain — not sent." in md
    assert "mailto:" not in md and "submitted" not in md.lower() and "sent to" not in md.lower()
